package com.axsos.project.repositores;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;

import com.axsos.project.models.OrderItem;

@Repository
public interface OrderItemRepository extends JpaRepository<OrderItem, Long>{
	// one row per calendar day (in "yyyy-MM-dd" form) with that day's revenue,
	// only for days on/after "since" - used to build the dashboard's daily sales chart
	@Query("SELECT FUNCTION('DATE_FORMAT', oi.createdAt, '%Y-%m-%d'), SUM(oi.quantity * oi.price) "
			+ "FROM OrderItem oi WHERE oi.product.store.id = :storeId AND oi.createdAt >= :since "
			+ "GROUP BY FUNCTION('DATE_FORMAT', oi.createdAt, '%Y-%m-%d') "
			+ "ORDER BY FUNCTION('DATE_FORMAT', oi.createdAt, '%Y-%m-%d')")
	List<Object[]> findDailySalesByStoreId(@Param("storeId") Long storeId, @Param("since") LocalDateTime since);

	// units sold for a single product (used on the product cards)
	@Query("SELECT COALESCE(SUM(oi.quantity), 0) FROM OrderItem oi WHERE oi.product.id = :productId")
	Long sumQuantityByProductId(@Param("productId") Long productId);

	// revenue generated by a single product (used on the product cards)
	@Query("SELECT COALESCE(SUM(oi.quantity * oi.price), 0.0) FROM OrderItem oi WHERE oi.product.id = :productId")
	Double sumRevenueByProductId(@Param("productId") Long productId);

	// total revenue across the whole store (used for the summary tiles)
	@Query("SELECT COALESCE(SUM(oi.quantity * oi.price), 0.0) FROM OrderItem oi WHERE oi.product.store.id = :storeId")
	Double sumRevenueByStoreId(@Param("storeId") Long storeId);

	// total units sold across the whole store (used for the summary tiles)
	@Query("SELECT COALESCE(SUM(oi.quantity), 0) FROM OrderItem oi WHERE oi.product.store.id = :storeId")
	Long sumQuantityByStoreId(@Param("storeId") Long storeId);
}
